# name: Nightly Terraform Apply

# on:
#   schedule:
#     - cron: '0 21 * * *'  # 9 PM UTC = midnight Turkey time (UTC+3 currently)
#   workflow_dispatch:       # Manual trigger

# permissions:
#   contents: read
#   id-token: write

# env:
#   AWS_TF_ROLE_ARN: ${{ secrets.AWS_TF_ROLE_ARN }}
#   TF_VAR_github_organization: "Bilgisayar-Kavramlari-Toplulugu"
#   TF_VAR_github_token: ${{ secrets.ORG_PAT }}
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# jobs:
#   terraform-nightly-apply:
#     name: Terraform Nightly Apply
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v5

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
#         with:
#           terraform_version: "1.13.5"

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v5
#         with:
#           role-to-assume: ${{ env.AWS_TF_ROLE_ARN }}
#           aws-region: eu-west-2

#       - name: Terraform Init
#         id: init
#         run: terraform init

#       - name: Terraform Validate
#         id: validate
#         run: terraform validate

#       - name: Terraform Plan
#         id: plan
#         run: terraform plan -no-color

#       - name: Terraform Apply
#         id: apply
#         run: terraform apply -auto-approve
